# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/plywa/OneDrive/Pulpit/semseter4/Semester project/constrains/Zedboard-Mastergsodarnine.xdc

# Block Designs: bd/sodar19/sodar19.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar19 || ORIG_REF_NAME==sodar19} -quiet] -quiet

# IP: bd/sodar19/ip/sodar19_processing_system7_0_0/sodar19_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar19_processing_system7_0_0 || ORIG_REF_NAME==sodar19_processing_system7_0_0} -quiet] -quiet

# IP: bd/sodar19/ip/sodar19_myip_sodar19_0_0/sodar19_myip_sodar19_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar19_myip_sodar19_0_0 || ORIG_REF_NAME==sodar19_myip_sodar19_0_0} -quiet] -quiet

# IP: bd/sodar19/ip/sodar19_xadc_wiz_0_0/sodar19_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar19_xadc_wiz_0_0 || ORIG_REF_NAME==sodar19_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/sodar19/ip/sodar19_pwm_top_0_1/sodar19_pwm_top_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar19_pwm_top_0_1 || ORIG_REF_NAME==sodar19_pwm_top_0_1} -quiet] -quiet

# IP: bd/sodar19/ip/sodar19_xbar_0/sodar19_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar19_xbar_0 || ORIG_REF_NAME==sodar19_xbar_0} -quiet] -quiet

# IP: bd/sodar19/ip/sodar19_auto_pc_0/sodar19_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar19_auto_pc_0 || ORIG_REF_NAME==sodar19_auto_pc_0} -quiet] -quiet

# IP: bd/sodar19/ip/sodar19_ps7_0_axi_periph_0/sodar19_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar19_ps7_0_axi_periph_0 || ORIG_REF_NAME==sodar19_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sodar19/ip/sodar19_rst_ps7_0_100M_0/sodar19_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar19_rst_ps7_0_100M_0 || ORIG_REF_NAME==sodar19_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/sodar19/sodar19_ooc.xdc
