# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/plywa/Digital designe vivado/sodar_19_cp/sodar_19_cp.srcs/sources_1/bd/sodar_19_cp/ip/sodar_19_cp_xbar_0/sodar_19_cp_xbar_0.xci
# IP: The module: 'sodar_19_cp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/plywa/Digital designe vivado/sodar_19_cp/sodar_19_cp.srcs/sources_1/bd/sodar_19_cp/ip/sodar_19_cp_xbar_0/sodar_19_cp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sodar_19_cp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/plywa/Digital designe vivado/sodar_19_cp/sodar_19_cp.srcs/sources_1/bd/sodar_19_cp/ip/sodar_19_cp_xbar_0/sodar_19_cp_xbar_0.xci
# IP: The module: 'sodar_19_cp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/plywa/Digital designe vivado/sodar_19_cp/sodar_19_cp.srcs/sources_1/bd/sodar_19_cp/ip/sodar_19_cp_xbar_0/sodar_19_cp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sodar_19_cp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
