# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/plywa/OneDrive/Pulpit/semseter4/Semester project/constrains/Zedboard-Mastergsodarninecp.xdc

# Block Designs: bd/sodar_19_cp/sodar_19_cp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar_19_cp || ORIG_REF_NAME==sodar_19_cp} -quiet] -quiet

# IP: bd/sodar_19_cp/ip/sodar_19_cp_processing_system7_0_0/sodar_19_cp_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar_19_cp_processing_system7_0_0 || ORIG_REF_NAME==sodar_19_cp_processing_system7_0_0} -quiet] -quiet

# IP: bd/sodar_19_cp/ip/sodar_19_cp_xadc_wiz_0_0/sodar_19_cp_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar_19_cp_xadc_wiz_0_0 || ORIG_REF_NAME==sodar_19_cp_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/sodar_19_cp/ip/sodar_19_cp_myip_sodarcp_0_0/sodar_19_cp_myip_sodarcp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar_19_cp_myip_sodarcp_0_0 || ORIG_REF_NAME==sodar_19_cp_myip_sodarcp_0_0} -quiet] -quiet

# IP: bd/sodar_19_cp/ip/sodar_19_cp_pwm_top_0_0/sodar_19_cp_pwm_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar_19_cp_pwm_top_0_0 || ORIG_REF_NAME==sodar_19_cp_pwm_top_0_0} -quiet] -quiet

# IP: bd/sodar_19_cp/ip/sodar_19_cp_xbar_0/sodar_19_cp_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar_19_cp_xbar_0 || ORIG_REF_NAME==sodar_19_cp_xbar_0} -quiet] -quiet

# IP: bd/sodar_19_cp/ip/sodar_19_cp_ps7_0_axi_periph_0/sodar_19_cp_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar_19_cp_ps7_0_axi_periph_0 || ORIG_REF_NAME==sodar_19_cp_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sodar_19_cp/ip/sodar_19_cp_rst_ps7_0_100M_0/sodar_19_cp_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar_19_cp_rst_ps7_0_100M_0 || ORIG_REF_NAME==sodar_19_cp_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/sodar_19_cp/ip/sodar_19_cp_auto_pc_0/sodar_19_cp_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sodar_19_cp_auto_pc_0 || ORIG_REF_NAME==sodar_19_cp_auto_pc_0} -quiet] -quiet

# XDC: bd/sodar_19_cp/sodar_19_cp_ooc.xdc
